# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_dataframe": "00_core.ipynb",
         "create_data": "00_core.ipynb",
         "train_model": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://raul.github.io/test_astronomer/"

git_url = "https://github.com/raul/test_astronomer/tree/master/"

def custom_doc_links(name): return None
